#######################################################################
# WARNING: This file automatically generated by Borg on <%=Date.create().format('{yyyy}-{MM}-{dd} {HH}:{mm}:{ss} {tz}')%>
#          If you need to edit this file, do so in the Borg repository.
#          Any change you make here WILL be overridden on assimilation.
#######################################################################

<% for defaults in @server.sudo.defaults: %>
Defaults      <%= defaults %>
<% end %>
<% if @server.sudo.agent_forwarding: %>
Defaults      env_keep+=SSH_AUTH_SOCK
<% end %>

# User privilege specification
root          ALL=(ALL) ALL

<% for a in @server.sudo.command_aliases: %>
Cmnd_Alias <%= a.name.toUpperCase() %> = <%= a.command_list.join ', ' %>
<% end %>

<% for user in @server.sudo.users: %>
<%= user %> ALL=(ALL) <%= if @server.sudo.passwordless then "NOPASSWD:" else "" %>ALL
<% end %>

<% for group in @server.sudo.groups: %>
# Members of the group '<%= group %>' may gain root privileges
%<%= group %> ALL=(ALL) <%= if @server.sudo.passwordless then "NOPASSWD:" else "" %>ALL
<% end %>
